//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeminarWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminars_tb
    {
        public int SeminartbId { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string Descriptiontb { get; set; }
        public string Preview { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
